on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      # - run: flutter build apk --debug --split-per-abi
      - run: flutter build apk --release
      # - run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%d.%b.%y_%I-%M%p')"
      - name: apk rename
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/getx_example_${{ steps.date.outputs.date }}.apk
      - name: Push to Releases
        uses: actions/upload-artifact@v1
        with:
            name: release-apk
            path: build/app/outputs/apk/release/getx_example_${{ steps.date.outputs.date }}.apk
        # uses: ncipollo/release-action@v1
        # with:
        #   artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
        #   tag: v1.0.${{ github.run_number }}
        #   token: ${{ secrets.TOKEN }}